set(CMAKE_SYSTEM_NAME "Android")
set(CMAKE_ANDROID_ARCH_ABI "armeabi-v7a")

set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "-Wl,-strip-debug")
set(CMAKE_C_FLAGS_INIT "-DLUA_USE_ANDROID" "-DLUA_USE_ANDROID_32")
set(CMAKE_CXX_FLAGS_INIT "-DLUA_USE_ANDROID" "-DLUA_USE_ANDROID_32")
