set(CMAKE_SYSTEM_NAME "Android")
set(CMAKE_ANDROID_ARCH_ABI "x86_64")

set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "-Wl,-strip-debug")
set(CMAKE_C_FLAGS_INIT "-DLUA_USE_ANDROID")
set(CMAKE_CXX_FLAGS_INIT "-DLUA_USE_ANDROID")
