import json
import os
import re


SRC_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "src")
DEST_DIR = os.path.join(SRC_DIR, "generated")
API_JSON_PATH = os.path.join(SRC_DIR, "..", "lib", "godot-cpp", "gdextension", "extension_api.json")
PACKAGE_SEARCHER_SRC = os.path.join(SRC_DIR, "luaopen", "package_searcher.lua")
LUA_SCRIPT_GLOBALS_SRC = os.path.join(SRC_DIR, "script-language", "globals.lua")
PRIMITIVE_VARIANTS = [
    "bool",
    "int",
    "float",
]
UTILITY_FUNCTION_MAP = {
    "print": None,
    "typeof": None,
    "is_instance_valid": None,
}


def _to_variant_type(s: str) -> str:
    return "Variant::" + re.sub("([a-z])([A-Z])|([0-9])(Array)", r"\1\3_\2\4", s).upper()


def generate_utility_functions(utility_functions):
    lines = [
        "// This file was automatically generated by generate_code.py\n#undef register_utility_functions\n#define register_utility_functions(state)",
    ]
    for f in utility_functions:
        name = f["name"]
        funcname = UTILITY_FUNCTION_MAP.get(name, name)
        if funcname is None:
            continue
        if f.get("is_vararg", False):
            lines.append(f'\tstate.set("{name}", &_call_variadic_utility_function<{f.get("return_type", "void")}, "{name}", {f.get("hash")}>);')
        elif (
            f.get("return_type") not in PRIMITIVE_VARIANTS
            or any(arg["type"] not in PRIMITIVE_VARIANTS for arg in f.get("arguments", []))
        ):
            lines.append(f'\tstate.set("{name}", wrap_function(state, &UtilityFunctions::{funcname}));')
        else:
            lines.append(f'\tstate.set("{name}", &UtilityFunctions::{funcname});')
    return " \\\n".join(lines) + "\n"


def generate_enums(global_enums):
    lines = [
        "// This file was automatically generated by generate_code.py\n#undef register_global_enums\n#define register_global_enums(state)",
    ]
    for enum in global_enums:
        lines.append(f"\t/* {enum['name']} */")
        for value in enum["values"]:
            lines.append(f'\tstate.set("{value["name"]}", {value["value"]});')
    return " \\\n".join(lines) + "\n"


def generate_package_searcher():
    lines = [
        "// This file was automatically generated by generate_code.py",
        "const char package_searcher_lua[] = ",
    ]
    with open(PACKAGE_SEARCHER_SRC, "r", encoding="utf-8") as f:
        for line in f:
            line = line.replace("\\", "\\\\").replace('"', '\\"').rstrip("\r\n")
            lines.append('"' + line + '\\n"')
    lines.append(";")
    return "\n".join(lines)


def generate_lua_script_globals():
    lines = [
        "// This file was automatically generated by generate_code.py",
        "const char lua_script_globals[] = ",
    ]
    with open(LUA_SCRIPT_GLOBALS_SRC, "r", encoding="utf-8") as f:
        for line in f:
            line = line.replace("\\", "\\\\").replace('"', '\\"').rstrip("\r\n")
            lines.append('"' + line + '\\n"')
    lines.append(";")
    return "\n".join(lines)


def generate_variant_type_constants(builtin_classes):
    lines = [
        "// This file was automatically generated by generate_code.py",
        "#include <godot_cpp/variant/variant.hpp>",
        "using namespace godot;",
        "",
        "inline Variant variant_constant_named(Variant::Type type, const StringName& name) {",
        "\tstatic Dictionary constants;",
        "\tif (constants.is_empty()) {",
    ]
    for cls in builtin_classes:
        constants = cls.get("constants", [])
        enums = cls.get("enums", [])
        if constants or enums:
            lines.append("\t\t{")
            lines.append(f"\t\t\tDictionary c;")
            for constant in constants:
                value = constant['value'].replace("inf", "INFINITY")
                # Projection in C++ cannot be initialized with all 16 numbers, we need 4 columns instead T_T
                if cls["name"] == "Projection":
                    value_list = list(value)
                    value_list.insert(57, "}")
                    value_list.insert(47, "{")
                    value_list.insert(45, "}")
                    value_list.insert(35, "{")
                    value_list.insert(33, "}")
                    value_list.insert(23, "{")
                    value_list.insert(21, "}")
                    value_list.insert(11, "{")
                    value = "".join(value_list)
                lines.append(f"\t\t\tc[\"{constant['name']}\"] = {value};")
            for enum in enums:
                lines.append(f"\t\t\tDictionary {enum['name']};")
                for value in enum["values"]:
                    lines.append(f"\t\t\t{enum['name']}[\"{value['name']}\"] = {value['value']};")
                lines.append(f"\t\t\tc[\"{enum['name']}\"] = {enum['name']};")
            lines.append(f"\t\t\tconstants[{_to_variant_type(cls['name'])}] = c;")
            lines.append("\t\t}")
    lines.append("\t}")
    lines.append("\tif (constants.has(type)) {")
    lines.append("\t\tDictionary c = constants[type];")
    lines.append("\t\treturn c[name];")
    lines.append("\t}")
    lines.append("\treturn Variant();")
    lines.append("}")
    return "\n".join(lines)



def main():
    with open(API_JSON_PATH, encoding="utf-8") as f:
        api = json.load(f)
    
    os.makedirs(DEST_DIR, exist_ok=True)
    with open(os.path.join(DEST_DIR, "utility_functions.hpp"), "w") as f:
        code = generate_utility_functions(api["utility_functions"])
        f.write(code)

    with open(os.path.join(DEST_DIR, "global_enums.hpp"), "w") as f:
        code = generate_enums(api["global_enums"])
        f.write(code)
    
    with open(os.path.join(DEST_DIR, "package_searcher.h"), "w") as f:
        code = generate_package_searcher()
        f.write(code)
    
    with open(os.path.join(DEST_DIR, "lua_script_globals.h"), "w") as f:
        code = generate_lua_script_globals()
        f.write(code)
    
    with open(os.path.join(DEST_DIR, "variant_type_constants.hpp"), "w") as f:
        code = generate_variant_type_constants(api["builtin_classes"])
        f.write(code)


if __name__ == "__main__":
    main()
