set(CMAKE_SYSTEM_NAME "iOS")
set(CMAKE_OSX_ARCHITECTURES "arm64" CACHE STRING "")

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "-Wl,-S -Wl,-x")
set(CMAKE_C_FLAGS_INIT "-DLUA_USE_IOS")
set(CMAKE_CXX_FLAGS_INIT "-DLUA_USE_IOS")
